
services:
  gpt4free:
    image: hlohaus789/g4f:latest
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - '8038:8080'
      - '1337:1337'
      - '7900:7900'
